### PR TITLE
rendering: Avoid prepending URL prefix to links that start with a scheme

### LINKED ISSUE #747: xmpp URL generation breaks
given
```
[foo@bar.tld](xmpp:foo@bar.tld)
```
the following is generated:
```
<a href="http://127.0.0.1:1111/xmpp:foo@bar.tld">foo@bar.tld</a>
```

Is this intended Markdown behavior or can this parsing of URIs be improved?

Expected result was an xmpp:... in the href.

### LINKED ISSUE #816: tel: links get erroneously absolutized
# Bug Report

When Zola renders a Markdown file with `tel:` links e.g.

    [(123) 456-7890](tel:+11234567890)

It incorrectly prepends the absolute path to the directory containing the page containing the link.

So instead of e.g.

    <a href="tel:+11234567890">(123) 456-7890</a>

It generates

    <a href="https://mysite.com/mydir/tel:+11234567890">(123) 456-7890</a>

## Environment

Zola version: zola 0.6.0

## Expected Behavior
Zola should generate HTML links with the verbatim URL from markdown links with `tel:` prefixes

## Current Behavior
Zola generates HTML links with the path to directory containing the the page containing the link prefixing `tel:` urls.

## Step to reproduce
Create a markdown file in a Zola site containing a link to a `tel:` URL.

### PR DESCRIPTION
**Pull request by zaeleus**
Links that start with a scheme (e.g., "tel:18008675309") inadvertently
had a URL prefix prepended. Previously, only `mailto:` was handled, but
given the sheer number of [registered URI schemes][uri-schemes], a loose
pattern matcher is used to detect schemes instead.

External links, as identified by the renderer, are now limited to `http`
and `https` schemes.

Fixes #747 and fixes #816.

[uri-schemes]: https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

---

**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [x] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

File: components/rendering/src/markdown.rs [hunk 1]
```diff
@@ -60,11 +61,31 @@ fn find_anchor(anchors: &[String], name: String, level: u8) -> String {
...
+// Returns whether the given string starts with a schema.
+//
+// Although there exists [a list of registered URI schemes][uri-schemes], a link may use arbitrary,
+// private schemes. This function checks if the given string starts with something that just looks
+// like a scheme, i.e., a case-insensitive identifier followed by a colon.
+//
+// [uri-schemes]: https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml
+fn starts_with_schema(s: &str) -> bool {
+    lazy_static! {
+        static ref PATTERN: Regex = Regex::new(r"^[0-9A-Za-z\-]+:").unwrap();
```
Comment (Keats) [inline components/rendering/src/markdown.rs:73]: can you move that towards the top of the file to match the other lazy_static usage in the crate? With a name like URL_SCHEMA_PATTERN for example.

**Review by Keats — CHANGES_REQUESTED** [review]
A small change but everything looks perfect otherwise.

**Comment by Keats** [comment]
Thanks!
