### PR TITLE
Fix shortcode/continue-reading parsing with inline HTML (smaller version)

### LINKED ISSUE #2565: Broken shortcodes on 0.19
I had a shortcode called `email` which contained my email address for reasons, and used it as such

```
<a name="contact-me" href="mailto:{{ email() }}">{{ email() }}</a>
```

This used to work but I have since upgraded to 0.19.1 and it simply outputs @@ZOLA_SC_PLACEHOLDER@@

I had to move the entire tag into the shortcode for it to work again, but this smells like a bug and a regression to me.

### PR DESCRIPTION
**Pull request by clarfonthey**
Version of #2581 with the new summary cutoff behaviour removed. (It now cuts off mid-paragraph like before, but doesn't do anything special about it.)

Done on master branch so it can presumably be released as a new micro version, but can move to next branch if preferred.

Supersedes #2601, fixes #2565.

### CODE REVIEW

File: components/markdown/tests/summary.rs [hunk 1]
```diff
@@ -45,3 +42,32 @@ And some content after
...
+* Program <!-- more --> something
+* Eat
+* Sleep
+    "#,
+    );
+    insta::assert_snapshot!(body);
+}
+
+#[test]
+fn foontnotes_summary() {
```
Comment (ta-nishq) [inline components/markdown/tests/summary.rs]: nit: maybe you meant this (similar change for snap file)
```suggestion
fn footnotes_summary() {
```

File: components/markdown/src/markdown.rs [hunk 2]
```diff
@@ -679,17 +684,15 @@ pub fn markdown_to_html(
...
-                        has_summary = true;
-                        events.push(Event::Html(CONTINUE_READING.into()));
-                        continue;
-                    }
-                    if !contains_shortcode(text.as_ref()) {
-                        events.push(Event::Html(text));
-                        continue;
-                    }
-
+                Event::Html(text) | Event::InlineHtml(text)
```
Comment (Keats) [inline components/markdown/src/markdown.rs]: I believe it might better to remove the InlineHtml from there for now so you don't get broken HTML

**Review by Keats — CHANGES_REQUESTED** [review]
That should be on next still, there will be a 0.19.2 release after this gets merged.

File: components/markdown/src/markdown.rs (hunk 2 above)
Comment (clarfonthey) [reply components/markdown/src/markdown.rs]: That's fair; I'll make that change but leave in the test that shows that there's no summary when this happens.

**Review by Keats — APPROVED** [review]

**Comment by Keats** [comment]
Nice thanks
