### PR TITLE
Escape path for live reload. Fix #1247.

### LINKED ISSUE #1247: Live reload protocol error (emits invalid JSON due to Windows style path separator)
# Bug Report

## Environment

Zola version: 0.12.2  
Windows 10.0.18363 Build 18363

## Expected Behavior
I expect an updates to my files to automatically reload the browser window.

## Current Behavior
LiveReload logs a protocol error due to invalid JSON.
These are the errors:
```
livereload.js?port=1024&mindelay=10:1 LiveReload protocol error (unparsable JSON) after receiving data: "
                    {
                        "command": "reload",
                        "path": "/sass\main.scss",
                        "originalPath": "",
                        "liveCSS": true,
                        "liveImg": true,
                        "protocol": ["http://livereload.com/protocols/official-7"]
                    }"..
livereload.js?port=1024&mindelay=10:1 LiveReload protocol error (unparsable JSON) after receiving data: "
                    {
                        "command": "reload",
                        "path": "D:\Projects\VSC\zola-test\templates\index.html",
                        "originalPath": "",
                        "liveCSS": true,
                        "liveImg": true,
                        "protocol": ["http://livereload.com/protocols/official-7"]
                    }"..
```
The first is what occurs when modifying `sass/main.scss`, the latter is what occurs when modifying the template `templates/index.html`.

The JSON is invalid due to unescaped Windows-style path separators.

## Step to reproduce

1. Run `zola init zola-test`
2. `cd zola-test`
3. `zola serve`
4. Navigate to http://127.0.0.1:1111/
5. Open the browser's developer console
6. Create a new file at `zola-test/templates/index.html`
7. Observe the error: ```LiveReload protocol error (unparsable JSON) after receiving data: "
                    {
                        "command": "reload",
                        "path": "D:\Projects\VSC\zola-test\templates\index.html",
                        "originalPath": "",
                        "liveCSS": true,
                        "liveImg": true,
                        "protocol": ["http://livereload.com/protocols/official-7"]
                    }"..```

### PR DESCRIPTION
**Pull request by Aidiakapi**
Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes

* [x] Are you doing the PR on the `next` branch?

This is a fix for #1247.

### CODE REVIEW

File: src/cmd/serve.rs [hunk 1]
```diff
@@ -154,13 +154,13 @@ fn rebuild_done_handling(broadcaster: &Option<Sender>, res: Result<()>, reload_p
...
                     {{
                         "command": "reload",
-                        "path": "{}",
+                        "path": {},
                         "originalPath": "",
                         "liveCSS": true,
                         "liveImg": true,
                         "protocol": ["http://livereload.com/protocols/official-7"]
                     }}"#,
-                        reload_path
```
Comment (Keats) [inline src/cmd/serve.rs]: I think we can write that one by hand, I don't really understand why this fixes the problem tbh

Comment (Aidiakapi) [reply src/cmd/serve.rs]: The problem isn't the path, the path's fine, the problem is that `"D:\Some\Directory\path.html"` is not valid JSON. Because `\` like in Rust, is an escape sequence, so it fails to parse. It should become `"D:\\Some\\Directory\\path.html"`. I chose `serde_json` because it's already in the dependency hierarchy anyways (the templates use it).

Comment (Keats) [reply src/cmd/serve.rs]: I see! Can you rebase? The tests should pass after that

**Comment by Aidiakapi** [comment]
Ah, GH's UI did a merge, not rebase. I'll resolve it locally.

File: src/cmd/serve.rs (hunk 1 above)
Comment (Aidiakapi) [reply src/cmd/serve.rs]: Ah yeah, didn't see the commit that snuck in there. It's done now.

Comment (Aidiakapi) [reply src/cmd/serve.rs]: There's still something messed up in there. I'll look into it I guess. I'll just hard reset and patch.

Comment (Aidiakapi) [reply src/cmd/serve.rs]: Alright, should be all good now.

**Comment by Keats** [comment]
Perfect thanks!
