### PR TITLE
Exclude paginated pages in sitemap

### LINKED ISSUE #2527: Paginated pages should be absent from sitemap.xml
# Bug Report

I am using pagination to show blog posts. I have enabled sitemap.xml. I use ahrefs for SEO site audits. It shows me [this](https://help.ahrefs.com/en/articles/2652498-non-canonical-page-in-sitemap-error-in-site-audit) issue which arises because [my sitemap](https://bauva.com/sitemap.xml) has links for paginated pages which it shouldn't since the links for all blog posts and the link for the list of blog post is there.

## Environment

Zola version: 0.18.0

## Expected Behavior

The /blog/ URL should be a part of sitemap.xml along with all the blog articles but not /blog/page/1/.

## Current Behavior

The paginated pages, i.e. /blog/page/1/, are a part of sitemap.xml, which makes search engines' lives difficult, and it could possibly lead to issues in indexing.

## Step to reproduce

Switch on pagination and sitemap generation.

### PR DESCRIPTION
**Pull request by pranitbauva1997**
This fixes #2527. @Keats, Can you please have a look at this and suggest improvements?

**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [x] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

File: components/config/src/config/mod.rs [hunk 1]
```diff
@@ -98,6 +98,9 @@ pub struct Config {
     pub markdown: markup::Markdown,
     /// All user params set in `[extra]` in the config
     pub extra: HashMap<String, Toml>,
+
+    /// Whether to exclude paginated pages in sitemap
+    pub exclude_paginated_pages_in_sitemap: bool,
```
Comment (Keats) [inline components/config/src/config/mod.rs]: Bikeshedding: i don't know whether it should go on another nested level in the config since we do regret top level fields everytime.. Maybe a seo struct?

I believe it should also be an enum:
- none
- first only
- all

since i did see some people indexing only the first page.

File: docs/content/documentation/templates/pagination.md [hunk 2]
```diff
@@ -52,6 +52,13 @@ A paginated taxonomy gets two variables aside from the `paginator` variable:
 
 See the [taxonomies page](@/documentation/templates/taxonomies.md) for a detailed version of the types.
 
+## SEO
+
+It is preferable to not include paginated pages in sitemap since they are non-canonical pages as explained
```
Comment (Keats) [inline docs/content/documentation/templates/pagination.md]: I would avoid making a call like that since it seems there are a lot of opinions: https://www.reddit.com/r/TechSEO/comments/10gfiob/should_pagination_pages_be_included_in_your/
Just describe the setting behaviour

File: docs/content/documentation/templates/pagination.md [hunk 3]
```diff
@@ -52,6 +52,13 @@ A paginated taxonomy gets two variables aside from the `paginator` variable:
...
+[here](https://help.ahrefs.com/en/articles/2652498-non-canonical-page-in-sitemap-error-in-site-audit) and
```
Comment (Keats) [inline docs/content/documentation/templates/pagination.md]: let's not include external links

**Review by Keats — CHANGES_REQUESTED** [review]

File: docs/content/documentation/templates/pagination.md (hunk 3 above)
Comment (pranitbauva1997) [reply docs/content/documentation/templates/pagination.md]: Understood

File: docs/content/documentation/templates/pagination.md (hunk 2 above)
Comment (pranitbauva1997) [reply docs/content/documentation/templates/pagination.md]: Makes sense.

File: components/config/src/config/mod.rs (hunk 1 above)
Comment (pranitbauva1997) [reply components/config/src/config/mod.rs]: Let's take an example of my site https://bauva.com since I have tested this PR on it. The [blog list page](https://bauva.com/blog/) is paginated and it contains the link to the next page. The current sitemap includes `/blog/` and `/blog/page/1/` and `/blog/page/2/`. After the current PR, the sitemap includes `/blog/` which can still work for search engines to discover the other paginated pages because the "next" and "prev" buttons. Also for the current behaviour `/blog/` and `/blog/page/1/` are the exact same pages which IMO should be avoided.

If we add another option like first only, the sitemap would contain `/blog/` and `/blog/page/1/` which will cause the same non-canonical page problem.

**Comment by pranitbauva1997** [comment]
@Keats Can you please re-review this?

File: components/config/src/config/mod.rs (hunk 1 above)
Comment (Keats) [reply components/config/src/config/mod.rs]: I think let's still make it a string because otherwise it will be a breaking change if we decide to have 3 behaviours. Maybe `paginated_pages_in_sitemap` as a name?

Comment (pranitbauva1997) [reply components/config/src/config/mod.rs]: Sure

**Comment by pranitbauva1997** [comment]
@Keats Made the required changes of using a string value instead of boolean so that we can further expand the scope by including other options. Can you please re-review?

File: components/config/src/config/mod.rs [hunk 4]
```diff
@@ -102,6 +102,8 @@ pub struct Config {
     pub generate_sitemap: bool,
     /// Enables the generation of robots.txt
     pub generate_robots_txt: bool,
+    /// Whether to exclude paginated pages in sitemap; can take values "none", "all"
+    pub exclude_paginated_pages_in_sitemap: String,
```
Comment (Keats) [inline components/config/src/config/mod.rs]: Sorry I meant something like `LinkCheckerLevel` where it's a String for the end user but we do turn it into a Rust enum: https://github.com/getzola/zola/blob/master/components/config/src/config/link_checker.rs#L7-L36

**Review by Keats — CHANGES_REQUESTED** [review]

File: components/config/src/config/mod.rs (hunk 4 above)
Comment (pranitbauva1997) [reply components/config/src/config/mod.rs]: @Keats, just to clarify, do you mean that the user behaviour of the PR in its current state is accurate but the internal data structures need to be changed to make it more extensible in future?

If that's the case, won't the refactor make sense when there are things to extend in the future? But if user behaviour needs to change, I should make that change in this PR.

Comment (Keats) [reply components/config/src/config/mod.rs]: You're correct. The main thing is that using an enum with serde serialization you will get error messages if you use invalid string values. Here they will just be ignored which isn't great.

Comment (pranitbauva1997) [reply components/config/src/config/mod.rs]: Got it, let me make the change right away

**Comment by pranitbauva1997** [comment]
@Keats Made the changes and tested them on my website. Earlier wrong values weren't throwing errors. Now, they are throwing descriptive errors.

**Review by Keats — APPROVED** [review]
Nice, thanks!

**Comment by pranitbauva1997** [comment]
@Keats thanks for approving the PR. This is my first contribution over here, so what would be the next steps? Please let me know if there is anything to be done from my side.

**Comment by Keats** [comment]
Nothing, that's all good!
