### PR TITLE
Make ignored_content work with nested paths and directories

### LINKED ISSUE #1701: Nested directory globs with ignored_content
What I'd like to do is have this work: `ignored_content = ["albums/**/*.{jpg,jpeg,png}"]`. Basically ignore any images in `content/albums` _and_ all sub-folders of that. This does not work.

`ignored_content = ["*.{jpg,jpeg,png}"]` works, but it ignores all images in `content` basically.

I think https://github.com/getzola/zola/issues/481 says this should work, but it may just be referring to specifying a particular folder.

I'm using `v0.15.2`.

### PR DESCRIPTION
**Pull request by kartva**
**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

resolves #1701 

Sanity check:
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes

* [X] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [X] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

**Comment by DesmondWillowbrook** [comment]
resolves #1701

**Comment by kartva** [comment]
This may break some config files if they had a filter which included directories (like `"foo/bar/*.xlsx"`) - previously Zola would ignore _all_ `*.xlsx` but now only `foo/bar/*.xlsx`. I don't think anyone relied on this behavior, though.

**Comment by Keats** [comment]
Can you rebase the PR?

**Comment by kartva** [comment]
Better now?

**Comment by Keats** [comment]
Hm no, it still contains lots of unrelated commits from master. The easiest way would be reset --hard on master and cherrypick the 2 relevant commits on it rather than merging

**Comment by DesmondWillowbrook** [comment]
I should be cherry-picking commits on top of next, right?

**Comment by kartva** [comment]
Is it somewhat better now?

File: components/config/src/config/mod.rs [hunk 1]
```diff
@@ -561,21 +561,24 @@ ignored_content = []
...
+        assert_eq!(g.len(), 3);
         assert!(g.is_match("foo.graphml"));
         assert!(g.is_match("foo.iso"));
         assert!(!g.is_match("foo.png"));
         assert!(g.is_match("foo.py2"));
         assert!(g.is_match("foo.py3"));
         assert!(!g.is_match("foo.py"));
+        assert!(g.is_match("foo/bar/target"));
+        assert!(g.is_match("foo/bar/baz/temp_folder"));
+        assert!(g.is_match("temp_folder"));
```
Comment (Keats) [inline components/config/src/config/mod.rs:583]: can you add some more test examples?

```
assert!(g.is_match("my/isos/foo.iso"));
assert!(g.is_match("content/poetry/zen.py"));
```

Just to assert that single files glob still work without striping the prefix.

**Review by Keats — CHANGES_REQUESTED** [review]
Looks good, just a small tweak needed to a test

File: components/config/src/config/mod.rs (hunk 1 above)
Comment (kartva) [reply components/config/src/config/mod.rs:583]: `assert!(g.is_match("content/poetry/zen.py"));` actually won't match since the pattern is `"*.py?"` (another test case `assert!(!g.is_match("foo.py"));` confirms that.

But yes, I'll add the rest.

**Comment by kartva** [comment]
Done? GitHub still shows "Changes requested" even if I marked it as resolved, so I'm not sure.

**Review by Keats — APPROVED** [review]
Yep sorry it's good
