### PR TITLE
Fix --base-url improper path and protocol handling using `zola serve`

### LINKED ISSUE #2170: --base-url ignored by serve
# Bug Report
The option `-u` or `--base-url` is not taken into account with the `serve` command.

## Environment

Zola version: 0.17.2

## Expected Behavior
With the command `zola serve -u 127.0.0.1/test/ -O`, I was expecting the server to open this URL and to make the site available at this URL.

## Current Behavior
- the command opens this URL: `http://127.0.0.1:1111/`
- the site is only partially available. The CSS and static items aren't found.
- opening `http://127.0.0.1:1111/test/` leads to a 404 answer from the server.

## Step to reproduce
Type the following command:

`zola serve -u 127.0.0.1/test/ -O`

The output is:

```log
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 14 pages (0 orphan) and 1 sections
Done in 62ms.

Web server is available at http://127.0.0.1:1111

Listening for changes in \\?\D:\projects\web\test_blog\{config.toml,content,sass,static,templates}
Press Ctrl+C to stop
```

The browser opens this page: `http://127.0.0.1:1111/`

## Other information

My config.toml file specifies a base URL on github.io. When I publish the website, it mostly works there except a few dangling URLs that I need to debug.

Used with the default options, e.g. `zola serve -O`, it works fine too. It just makes it difficult to check those dangling links with a more realistic URL that includes a path after the IP.

### PR DESCRIPTION
**Pull request by jamwil**
Correctly parse the protocol and path from the base url, and differentiate between the bound interface and the base URL when using `zola serve`.

Closes #2170.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [x] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

File: src/cmd/serve.rs [hunk 1]
```diff
@@ -240,6 +240,39 @@ fn rebuild_done_handling(broadcaster: &Sender, res: Result<()>, reload_path: &st
     }
 }
 
+fn construct_url(base_url: &str, no_port_append: bool, interface_port: u16) -> String {
```
Comment (Keats) [inline src/cmd/serve.rs:339]: With all the dependencies we're pulling, we don't pull the [url crate](https://crates.io/crates/url) ?

Comment (jamwil) [reply src/cmd/serve.rs:339]: I don't believe so—at least not as a first-party dependency.

**Comment by jamwil** [comment]
I'm marking this as Ready for Review.

The discussion in #2170 can be split into two separate features—the first being to properly parse the base_url so that `zola serve` works at various endpoints, including https endpoints. I believe this PR handles that use case without any changes to existing documentation.

The second feature requested in #2170 is to allow arbitrary paths while serving the content from a static /public directory (or wherever it is configured). This ventures into url_rewriting territory and, as far as I can tell, would require patching the [`make_service` block in `serve.rs`](https://github.com/jamwil/zola/blob/e09e36b2c24415eab09a81504a7a3df31dcd8501/src/cmd/serve.rs#L417).

~~I'm going to open this up to Allow edits by maintainers if anyone wants to delve further into it, and I'm open to guidance from someone that understands the codebase better than I do, but I think this is a suitable patch to tackle part of the issue as is.~~

See additional comment.

**Comment by jamwil** [comment]
I worked through the mounting problem. We should be able to serve at any arbitrary endpoint, including subpaths. This should close #2170.

File: src/cmd/serve.rs (hunk 1 above)
Comment (Keats) [reply src/cmd/serve.rs:339]: we do pull it in components/libs/Cargo.toml

Comment (jamwil) [reply src/cmd/serve.rs:339]: Oh, I see how that's structured now. Please advise on how you'd like me to proceed so we can get this patch merged. This works as is but I can rewrite it with the url crate if you prefer.

Comment (Keats) [reply src/cmd/serve.rs:339]: Let's use the url crate if it makes it simpler

**Comment by jamwil** [comment]
Looks like the changes I made to support paths introduced a regression for the https change. I'm investigating.

**Comment by jamwil** [comment]
Fixed the regression here. This should work as stated on the tin.

**Comment by Keats** [comment]
Can you cherry pick the commits on a rebased next branch?

**Comment by jamwil** [comment]
> Can you cherry pick the commits on a rebased next branch?

Yep, working on it. Some signatures have changed so it's a bit of an involved merge.

**Comment by jamwil** [comment]
@clarfonthey This PR has a lot of overlap with the work you did in January. Just wanted to give you a heads up so you can verify that it doesn't introduce any regressions to your work. It was a bit of a delicate merge.

**Comment by clarfonthey** [comment]
Thanks for the heads up @jamwil; any work I haven't merged is probably going to be redone anyway, so, I'm not worried about conflicts.

File: src/cmd/serve.rs (hunk 1 above)
Comment (jamwil) [reply src/cmd/serve.rs:339]: Having looked a little closer, I actually don't know that it makes it any simpler. The current implementation works well and is easy to follow IMO. If a maintainer wants to adjust it before merging that's totally fine.

Comment (clarfonthey) [reply src/cmd/serve.rs:339]: I personally think that the `url` crate would be an improvement since it would also allow validating URLs when parsing them from configs, but that can be reserved for a separate PR.

**Comment by jamwil** [comment]
@Keats Is there anything outstanding that we need to address?

File: src/cmd/serve.rs [hunk 2]
```diff
@@ -92,16 +92,34 @@ fn set_serve_error(msg: &'static str, e: errors::Error) {
...
 }
 
-async fn handle_request(req: Request<Body>, mut root: PathBuf) -> Result<Response<Body>> {
+async fn handle_request(
+    req: Request<Body>,
+    mut root: PathBuf,
+    base_path: String,
+) -> Result<Response<Body>> {
+    let path_str = req.uri().path();
+    if !path_str.starts_with(&base_path) {
```
Comment (Keats) [inline src/cmd/serve.rs:101]: What's the base_path?

File: src/cmd/serve.rs [hunk 3]
```diff
@@ -92,16 +92,34 @@ fn set_serve_error(msg: &'static str, e: errors::Error) {
     }
 }
 
-async fn handle_request(req: Request<Body>, mut root: PathBuf) -> Result<Response<Body>> {
+async fn handle_request(
```
Comment (Keats) [inline src/cmd/serve.rs:95]: This is starting to have a lot of logic that is not tested :/ 
I don't know the story with hyper in terms of tests, is it easy to add some to test this endpoint?

File: src/cmd/serve.rs (hunk 2 above)
Comment (jamwil) [reply src/cmd/serve.rs:101]: In the url `https://example.com/path/to/index.html`, base_path would be `/path/to/index.html`. It's derived on line 455.

File: src/cmd/serve.rs (hunk 3 above)
Comment (jamwil) [reply src/cmd/serve.rs:95]: I definitely agree there should be a more thorough testing framework around this (these changes and the preexisting logic). I would consider that outside the scope of this PR though as there was no endpoint testing on `serve.rs` prior and these particular changes are more of an issue fix than an enhancement.

I would be happy to open a subsequent PR to enhance the testing around this.

File: src/cmd/serve.rs (hunk 2 above)
Comment (Keats) [reply src/cmd/serve.rs:101]: But we can't get it from the Request? (I haven't looked at hyper in a looooong time)

Comment (jamwil) [reply src/cmd/serve.rs:101]: Oh—good thought. We likely can. I also am not up on hyper and have generally stuck to using primitives throughout this PR.

I'm happy to get more involved in the project and do a subsequent PR to add more tests and do some refactoring along these lines, but for the moment this is working code that fixes something that's currently broken. I think the focus should be on getting #2170 closed sooner than later and we can circle back on the implementation details.

File: src/cmd/serve.rs (hunk 3 above)
Comment (Keats) [reply src/cmd/serve.rs:95]: Yep that sounds good, thanks!
