### PR TITLE
Skip anchor checking for URL with prefix in config

### LINKED ISSUE #805: External link checker does not find GitHub anchors
I just updated my `blog_os` project from zola 0.7.0 to zola 0.9.0. It worked great and it even caught several invalid anchors in internal links. Thanks a lot for your work!

I noticed a problem when checking external links using `zola check`: For some URLs (mostly GitHub URLs), it reports an anchor as 'not found' even though it seems to exist. Some examples:

```
Error: Dead link in /home/runner/work/blog_os/blog_os/blog/content/first-edition/extra/cross-compile-libcore.md to https://github.com/japaric/rust-cross#the-target-triple: Anchor `#the-target-triple` not found on page
Dead link in /home/runner/work/blog_os/blog_os/blog/content/first-edition/extra/cross-compile-libcore.md to https://github.com/japaric/xargo#dependencies: Anchor `#dependencies` not found on page
Dead link in /home/runner/work/blog_os/blog_os/blog/content/first-edition/extra/naked-exceptions/03-returning-from-exceptions/index.md to https://github.com/rust-lang/rust/blob/c772948b687488a087356cb91432425662e034b9/src/librustc_back/target/mod.rs#L194-L214: Anchor `#L194-L214` not found on page
```

I think the reason is that GitHub uses IDs like `user-content-the-target-triple` instead of `the-target-triple` for its generated anchors. I'm not sure why the anchor still works without the `user-content` prefix. Maybe it's done in Javascript. Either way, I think that it might be worth to handle somehow, given that GitHub is a common link target.

### PR DESCRIPTION
**Pull request by TjeuKayim**
Fixes #805

`zola check`

The anchors of external URLs will not be checked if it starts with one of the configured prefixes.
So false positives can be put on the ignore list, like https://github.com/rust-lang/rust/blob/c772948b687488a087356cb91432425662e034b9/src/librustc_back/target/mod.rs#L194-L214: Anchor `#L194-L214 and https://caniuse.com/#feat=css-filters.

```toml
# Link Checker: skip anchor checking for external URLs that start with these prefixes
link_checker_skip_anchor_prefixes = [
    "https://caniuse.com/",
]
```

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [x] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

File: components/config/src/config.rs [hunk 1]
```diff
@@ -152,6 +153,8 @@ pub struct Config {
     #[serde(skip_serializing, skip_deserializing)] // not a typo, 2 are need
     pub extra_syntax_set: Option<SyntaxSet>,
 
+    pub link_checker: LinkChecker,
```
Comment (Keats) [inline components/config/src/config.rs:168]: I would like all config options to be in the config component directly.

**Review by Keats — CHANGES_REQUESTED** [review]
Just a small change, everything looks great otherwise.

File: components/config/src/config.rs (hunk 1 above)
Comment (TjeuKayim) [reply components/config/src/config.rs:168]: Okay, I can change that. Thanks for the feedback. 

What do you think about the LinkChecker config struct? This way it will be easier to add new options later, like the user agent. Should `check_url()` convert to a method? Or keep adding arguments while the link checker evolves?

File: components/config/src/config.rs [hunk 2]
```diff
@@ -152,6 +152,8 @@ pub struct Config {
     #[serde(skip_serializing, skip_deserializing)] // not a typo, 2 are need
     pub extra_syntax_set: Option<SyntaxSet>,
 
+    pub link_checker_skip_anchor_prefixes: Vec<String>,
```
Comment (Keats) [inline components/config/src/config.rs]: Sorry, I meant having the struct

```rust
#[derive(Clone, Debug, PartialEq)]
pub struct LinkChecker {
    /// Skip anchor checking for these URL prefixes
    pub skip_anchor_prefixes: Vec<String>,
}
```
in this file and use it in the config

File: components/link_checker/src/lib.rs [hunk 3]
```diff
@@ -46,39 +46,56 @@ impl LinkResult {
...
+        LinkChecker { skip_anchor_prefixes: Vec::new() }
+    }
+}
+
 lazy_static! {
     // Keep history of link checks so a rebuild doesn't have to check again
     static ref LINKS: Arc<RwLock<HashMap<String, LinkResult>>> = Arc::new(RwLock::new(HashMap::new()));
 }
 
-pub fn check_url(url: &str) -> LinkResult {
```
Comment (Keats) [inline components/link_checker/src/lib.rs:54]: this would mean that this stays a function that is `pub fn check_url(url: &str, config: &LinkChecker) -> LinkResult`. Adding new options to the LinkChecker makes it available automatically

**Review by Keats — CHANGES_REQUESTED** [review]

File: components/link_checker/src/lib.rs (hunk 3 above)
Comment (TjeuKayim) [reply components/link_checker/src/lib.rs:54]: So create link_checker should depend on crate config?

File: components/config/src/config.rs (hunk 2 above)
Comment (TjeuKayim) [reply components/config/src/config.rs]: Oh, I misunderstood your wording then.

**Comment by Keats** [comment]
Great, thanks!
