### PR TITLE
Fix shortcode handling in code-fences

### LINKED ISSUE #1708: Support for shortcodes in fenced code blocks
# Bug Report

## Environment

Zola version: 0.15.2

## Expected Behavior
*Tell us what should have happened.*

In previous versions of Zola, I was able to put shortcodes in fenced code blocks in order to give the viewer an idea of what the generated HTML of the shortcode would look like when used.

This is useful, for example, when giving examples of custom shortcodes in Zola themes.

## Current Behavior
*Tell us what happens instead of the expected behavior. If you are seeing an
error, please include the full error message and stack trace. You can get the
stacktrace of a panic by adding `RUST_BACKTRACE=1` when running a `zola` command.*

In the current version of Zola, these shortcodes just output `@@ZOLA_SC_PLACEHOLDER@@`.

## Step to reproduce
*Please provide the steps to reproduce the issue.
If the issue is hard to reproduce, please provide a sample repository or sample
that triggers the bug.*

To view this in action, clone [figbert/d3c3nt](https://github.com/figbert/d3c3nt) and run `zola serve` in the root directory. From there, navigate to `/posts/rich-content/` and scroll around.

### PR DESCRIPTION
**Pull request by liushuyu**
**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [X] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [N/A] Have you created/updated the relevant documentation page(s)?

------

This should fix #1708.

The fix is actually a workaround: by applying and capturing shortcode rendering output and then re-render them inside the code-fence context.

### CODE REVIEW

**Comment by Keats** [comment]
Can you add tests? It will need quite a few

**Comment by liushuyu** [comment]
> Can you add tests? It will need quite a few

Sure, I will add some tests.

**Comment by liushuyu** [comment]
Rebased. Code cleaned-up. Tests added.

**Comment by liushuyu** [comment]
This is basically a hack, but I think this is also the minimal changes required for fixing this issue.

There are three tests added to test the rendering behavior including a ~~bulls**t~~ all-star test to see whether the parser could correctly handle a bunch of weird constructs.

**Comment by liushuyu** [comment]
Is this good to merge? Or should I do something more than this?

File: components/rendering/src/markdown.rs [hunk 1]
```diff
@@ -242,7 +242,32 @@ pub fn markdown_to_html(
             match event {
                 Event::Text(text) => {
                     if let Some(ref mut code_block) = code_block {
-                        let html = code_block.highlight(&text);
+                        let html;
+                        if contains_shortcode(text.as_ref()) {
```
Comment (Keats) [inline components/rendering/src/markdown.rs:246]: very small style neat but `let html = if { .. } else { .. }` is a bit nicer imo

**Review by Keats — APPROVED** [review]
Just a small nit, no need to change it. Looks good, thanks!
