### PR TITLE
Adjust ImageMeta dimensions based on Exif orientation data

### LINKED ISSUE #2818: get_image_metadata does not handle EXIF rotation
# Bug Report

## Environment

Zola version: 0.20.0 (installed from winget)

## Expected Behavior
When processing an image that has rotation applied in the EXIF metadata, `get_image_metadata()` gives the correct (rotated) dimensions

## Current Behavior
`get_image_metadata()` ignores the EXIF rotation and returns the unrotated dimensions.  
This is not only undesirable for the user, but also inconsistent with `resize_image` which handles rotation correctly (compare #2445 that raised the equivalent issue there).

## Step to reproduce
Use a JPEG image with EXIF rotation of 90 degrees, and call `get_image_metadata` with its path as an argument.

### PR DESCRIPTION
**Pull request by Insprill**
The current handling of image dimensions when rotated with Exif data is relatively poor, as it's only handled in `ImageOp.perform`. This means that other image operations such as `get_image_metadata` and `resize_image` will be operating with the expected width and height flipped.

This proved to be problematic for a macro I had written to automatically create multiple scaled versions of images. It works fine for landscape images, but squishes portrait images into the size as if it wasn't rotated at all.
<details>
<summary>Macro code</summary>

```html
{% macro responsive_img(path, alt="", sizes="100vw", priority="auto", class="") -%}
  {% set img_fmt = "avif" %}
  {% set img_qlt = 70 %}

  {% set meta = get_image_metadata(path=path) %}
  {% set w1 = meta.width %}
  {% set w2 = meta.width / 2 | int %}
  {% set w3 = meta.width / 4 | int %}
  {% set w4 = meta.width / 8 | int %}
  {% set w5 = meta.width / 16 | int %}
  {% set w6 = meta.width / 32 | int %}

  {% set i1 = resize_image(path=path, width=w1, op="fit_width", format=img_fmt, quality=img_qlt) %}
  {% set i2 = resize_image(path=path, width=w2, op="fit_width", format=img_fmt, quality=img_qlt) %}
  {% set i3 = resize_image(path=path, width=w3, op="fit_width", format=img_fmt, quality=img_qlt) %}
  {% set i4 = resize_image(path=path, width=w4, op="fit_width", format=img_fmt, quality=img_qlt) %}
  {% set i5 = resize_image(path=path, width=w5, op="fit_width", format=img_fmt, quality=img_qlt) %}
  {% set i6 = resize_image(path=path, width=w6, op="fit_width", format=img_fmt, quality=img_qlt) %}

  <img
    class = "{{ class }}"
    src="{{ i6.url }}"
    srcset="
      {{ i1.url }} {{ w1 }}w,
      {{ i2.url }} {{ w2 }}w,
      {{ i3.url }} {{ w3 }}w,
      {{ i4.url }} {{ w4 }}w,
      {{ i5.url }} {{ w5 }}w,
      {{ i6.url }} {{ w6 }}w,
    "
    sizes="{{ sizes }}"
    alt="{{ alt }}"
    loading="lazy"
    fetchpriority="{{ priority }}"
  />
{%- endmacro %}
```

</details>

With the above macro and Zola v0.20.0, the following image is output:
DSC00819 14678d46ab9ae7d2

With this PR, the output is as expected:
DSC00819 854761b8da61362d

I initially wrote this to swap only the dimensions in the `read_image_metadata` default match arm. This fixed the issue for `get_image_metadata` but did not fix the issue for `resize_image`, which would still result in the same "before" image regardless of whether I gave `get_image_metadata`'s width or height to the width parameter. This was because it parsed its own copy of `ImageMeta` without correcting the rotation values. Because of this, and to avoid placing rotation corrections all over the codebase, I only applied it in `ImageMeta.read`, which covers both of my use cases, and potentially others that may otherwise have been missed. This doesn't affect the rotation handling in `ImageOp.perform` since it reads the image file directly, without the use of `ImageMeta`.

I haven't updated the documentation since I didn't see any mentions of rotation handling there. With this PR, it should be as expected, so I don't believe a mention is necessary, although I'll gladly write something up if requested.

This is my first time contributing to Zola, so please let me know if I should've done anything differently! I also haven't been working with Zola for too long, so I can't be certain this doesn't have any adverse effects, but everything appeared to be functioning fine on my site, and all tests are passing, so it would seem everything is good. A thorough review and testing should be done prior to merging, though, just to be safe.

Closes #2818

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [ ] Have you created/updated the relevant documentation page(s)?

### CODE REVIEW

File: components/imageproc/src/meta.rs [hunk 1]
```diff
@@ -21,7 +23,11 @@ impl ImageMeta {
     pub fn read(path: &Path) -> ImageResult<Self> {
         let reader = ImageReader::open(path).and_then(ImageReader::with_guessed_format)?;
         let format = reader.format();
-        let size = reader.into_dimensions()?;
+        let mut size = reader.into_dimensions()?;
```
Comment (Keats) [inline components/imageproc/src/meta.rs]: can we somehow get the exif metadata from the image object? So we don't have to read the file twice

Comment (Insprill) [reply components/imageproc/src/meta.rs]: Yup, image-rs has a function on `ImageDecoder` to get the raw Exif data. I made `get_orientation` take the raw Exif data and updated all the upstream usages (ImageMeta, ImageOp, tests) to get it this way.

**Review by Keats — APPROVED** [review]

**Comment by Keats** [comment]
Can you try to rebase + force push to see if it starts the CI? I don't understand

**Comment by Insprill** [comment]
I believe the CI issues are stemming from the `on` condition in the action. There's no `pull_request`[^1] entry, so it only runs for branches in the main repo[^2]. I'm not sure if this is directly related or not, but the `*` matcher for branch name also excludes any branches with a `/` in it's name[^3] (I ran into this when trying to run CI on my fork).

Perhaps something as simple as 
```yaml
on: [ push, pull_request ]
```
should be used instead? That's my usual go-to.

[^1]: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
[^2]: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#using-a-single-event
[^3]: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

**Comment by Keats** [comment]
ah that's weird yeah it should definitely have PR in there, I didn't notice it was missing

**Comment by Insprill** [comment]
Is there anything blocking this PR from being merged that I can help with?

**Comment by tarqd** [comment]
Thanks for sharing this PR! I'm running into this problem on my site as well. I'm getting image processing errors I did not see before in v0.20.0. 

```
Error: Failed to build the site
Error: Failed to process image: /Users/tarq/Development/stickywiki/web/content/stickers/2025/06/15/alien-on-lake/sticker.jpeg
Error: Reason: Format error decoding Jpeg: Error in decoding MCU. Reason Marker SOI found in bitstream, possibly corrupt jpeg
Error: Reason: Error in decoding MCU. Reason Marker SOI found in bitstream, possibly corrupt jpeg
```

Image info:

```
file sticker.jpeg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 300x300, segment length 20, Exif Standard: [TIFF image data, big-endian, direntries=12, manufacturer=Apple, model=iPhone 16 Pro, orientation=upper-right, xresolution=178, yresolution=186, resolutionunit=2, software=26.0, datetime=2025:06:15 14:16:12, hostcomputer=iPhone 16 Pro, GPS-Data], baseline, precision 8, 4032x3024, components 3

identify sticker.jpeg                 
sticker.jpeg JPEG 4032x3024 4032x3024+0+0 8-bit sRGB 2.04706MiB 0.000u 0:00.002
```

Exif:


```
ExifTool Version Number         : 13.25
File Name                       : sticker.jpeg
Directory                       : /Users/tarq/Development/stickywiki/web/content/stickers/2025/06/15/alien-on-lake
File Size                       : 2.1 MB
File Modification Date/Time     : 2025:06:17 18:51:13-04:00
File Access Date/Time           : 2025:07:01 19:38:56-04:00
File Inode Change Date/Time     : 2025:07:01 19:37:39-04:00
File Permissions                : -rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Exif Byte Order                 : Big-endian (Motorola, MM)
Make                            : Apple
Camera Model Name               : iPhone 16 Pro
Orientation                     : Rotate 90 CW
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Software                        : 26.0
Modify Date                     : 2025:06:15 14:16:12
Host Computer                   : iPhone 16 Pro
Color Space                     : Uncalibrated
Exif Image Width                : 4032
Exif Image Height               : 3024
Scene Capture Type              : Standard
Composite Image                 : General Composite Image
Compression                     : JPEG (old-style)
Thumbnail Offset                : 3256
Thumbnail Length                : 8206
MPF Version                     : 0100
Number Of Images                : 2
MP Image Flags                  : (none)
MP Image Format                 : JPEG
MP Image Type                   : Undefined
MP Image Length                 : 382869
MP Image Start                  : 1763626
Dependent Image 1 Entry Number  : 0
Dependent Image 2 Entry Number  : 0
Uniform Resource Name           : urn:iso:std:iso:ts:21496:-1
Profile CMM Type                : Apple Computer Inc.
Profile Version                 : 4.0.0
Profile Class                   : Display Device Profile
Color Space Data                : RGB
Profile Connection Space        : XYZ
Profile Date Time               : 2022:01:01 00:00:00
Profile File Signature          : acsp
Primary Platform                : Apple Computer Inc.
CMM Flags                       : Not Embedded, Independent
Device Manufacturer             : Apple Computer Inc.
Device Model                    : 
Device Attributes               : Reflective, Glossy, Positive, Color
Rendering Intent                : Perceptual
Connection Space Illuminant     : 0.9642 1 0.82491
Profile Creator                 : Apple Computer Inc.
Profile ID                      : ecfda38e388547c36db4bd4f7ada182f
Profile Description             : Display P3
Profile Copyright               : Copyright Apple Inc., 2022
Media White Point               : 0.96419 1 0.82489
Red Matrix Column               : 0.51512 0.2412 -0.00105
Green Matrix Column             : 0.29198 0.69225 0.04189
Blue Matrix Column              : 0.1571 0.06657 0.78407
Red Tone Reproduction Curve     : (Binary data 32 bytes, use -b option to extract)
Chromatic Adaptation            : 1.04788 0.02292 -0.0502 0.02959 0.99048 -0.01706 -0.00923 0.01508 0.75168
Blue Tone Reproduction Curve    : (Binary data 32 bytes, use -b option to extract)
Green Tone Reproduction Curve   : (Binary data 32 bytes, use -b option to extract)
HDR Gain Curve                  : (Binary data 1384 bytes, use -b option to extract)
Image Width                     : 4032
Image Height                    : 3024
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 4032x3024
Megapixels                      : 12.2
Create Date                     : 2025:06:15 14:16:12.035-04:00
Date/Time Original              : 2025:06:15 14:16:12.035-04:00
Modify Date                     : 2025:06:15 14:16:12-04:00
Thumbnail Image                 : (Binary data 8206 bytes, use -b option to extract)
MP Image 2                      : (Binary data 382869 bytes, use -b option to extract)
```

Attached is the image (in a zip to prevent GitHub processing): [sticker.jpeg.zip](https://github.com/user-attachments/files/21008904/sticker.jpeg.zip)

**Comment by tarqd** [comment]
Ah, this seems to happen on the `next` branch as well so I do not think this is related to this PR. Apologies for the confusion.
