### PR TITLE
Hard link serve panic fix

### LINKED ISSUE #2081: Errors in zola serve with hard_link_static = true
From https://github.com/getzola/zola/issues/1217#issuecomment-1141636610 by @koitsu

Can confirm: the issue only happens when using hard_link_static = true, and happens regardless if you have any static assets or not. It's as easy as this:

    Terminal 1: make sure you have a zola site that is working/building correctly
    Terminal 2: zola serve + whatever args (sans -f)
    Terminal 1: modify an .md file -- literally just open it up in vi, change nothing, and write it
    Terminal 2: Zola begins to report bizarre and unhelpful errors (I sure wish it showed what file/directory it was accessing that resulted in errno EEXIST).

Demonstration of above:
```
$ zola serve -i 0.0.0.0 -p 1111
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 1 pages (0 orphan) and 1 sections
Done in 124ms.

Listening for changes in /home/jdc/blog20{config.toml, content, sass, static, templates}
Press Ctrl+C to stop

Web server is available at http://0.0.0.0:1111

Change detected @ 2022-05-30 20:38:37
-> Content changed /home/jdc/blog20/content/blog/2022-05-30-welcome-to-dumb.md
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 1 pages (0 orphan) and 1 sections
Failed to build the site
Error: File exists (os error 17)
Done in 6ms.
```

### PR DESCRIPTION
**Pull request by Raymi306**
**IMPORTANT: Please do not create a Pull Request adding a new feature without discussing it first.**

The place to discuss new features is the forum: <https://zola.discourse.group/>
If you want to add a new feature, please open a thread there first in the feature requests section.

Sanity check:

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/getzola/zola/pulls) for the same update/change?

## Code changes
(Delete or ignore this section for documentation changes)

* [x] Are you doing the PR on the `next` branch?

If the change is a new feature or adding to/changing an existing one:

* [x] Have you created/updated the relevant documentation page(s)?
---
Fixes #2081

### CODE REVIEW

File: components/utils/src/fs.rs [hunk 1]
```diff
@@ -86,7 +86,16 @@ pub fn copy_file_if_needed(src: &Path, dest: &Path, hard_link: bool) -> Result<(
...
     if hard_link {
-        std::fs::hard_link(src, dest)?
+        if dest.exists() {
+            if let Err(e) = std::fs::remove_file(dest) {
+                console::error(&format!("File System Error, src: {:?}, dst: {:?}", src, dest));
+                return Err(e.into());
+            }
+        }
+        if let Err(e) = std::fs::hard_link(src, dest) {
+            console::error(&format!("File System Error, src: {:?}, dst: {:?}", src, dest));
```
Comment (Keats) [inline components/utils/src/fs.rs]: No need to import `console`, just return an error for both

**Review by Keats — CHANGES_REQUESTED** [review]

File: components/utils/src/fs.rs [hunk 2]
```diff
@@ -86,7 +86,12 @@ pub fn copy_file_if_needed(src: &Path, dest: &Path, hard_link: bool) -> Result<(
     }
 
     if hard_link {
-        std::fs::hard_link(src, dest)?
+        if dest.exists() {
+            std::fs::remove_file(dest)
+                .with_context(|| format!("Error removing file, dst: {:?}", dest))?;
```
Comment (Keats) [inline components/utils/src/fs.rs]: dst is not going to be clear to the end error, just put `Error removing file: {:?}`

File: components/utils/src/fs.rs [hunk 3]
```diff
@@ -86,7 +86,12 @@ pub fn copy_file_if_needed(src: &Path, dest: &Path, hard_link: bool) -> Result<(
...
+        }
+        std::fs::hard_link(src, dest)
+            .with_context(|| format!("Error linking file, src: {:?}, dst: {:?}", src, dest))?;
```
Comment (Keats) [inline components/utils/src/fs.rs]: Error linking file -> Error hard linking file

**Review by Keats — CHANGES_REQUESTED** [review]

**Review by Keats — APPROVED** [review]
Thanks!
