### PR TITLE
Footnote is now supported in headers

### LINKED ISSUE #569: Footnote in title don't work as expected
# Bug Report
Footnote link in header will appear prior to header.

## Environment
``` bash
❯ uname -srmo
Linux 4.14.90-1-MANJARO x86_64 GNU/Linux
❯ zola --version
zola 0.5.1
```

## Step to reproduce
content/test.md:
```markdown
+++
template = "page.html"
+++
# header[^1]

another[^2] footnote.

[^1]: footnote one
[^2]: footnote two
```
template/page.md:
```jinja
{{ page.content | safe }}
```
build command: `zola build`

## Expected Behavior
Output should be same as what `pulldown-cmark` out:
```html
<h1>header<sup class="footnote-reference"><a href="#1">1</a></sup></h1>
<p>another<sup class="footnote-reference"><a href="#2">2</a></sup> footnote.</p>
<div class="footnote-definition" id="1"><sup class="footnote-definition-label">1</sup>
<p>footnote one
<sup class="footnote-reference"><a href="#2">2</a></sup>: footnote two</p>
</div>
```

## Current Behavior
```html
<sup class="footnote-reference"><a href="#1">1</a></sup><h1 id="header">header</h1>
<p>another<sup class="footnote-reference"><a href="#2">2</a></sup> footnote.</p>
<div class="footnote-definition" id="1"><sup class="footnote-definition-label">1</sup>
<p>footnote one
<sup class="footnote-reference"><a href="#2">2</a></sup>: footnote two</p>
</div>
```

### PR DESCRIPTION
**Pull request by peng1999**
This fixes #569 .
    
`markdown_to_html` is heavily refactored, header-related things is
handled in a second pass.

<details>
  <summary>Sanity check:</summary>

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

## Code changes

* [x] Are you doing the PR on the `next` branch?

</details>

### CODE REVIEW

**Comment by Keats** [comment]
Thanks, I'll have a look at the PR later this week!

File: components/rendering/src/markdown.rs [hunk 1]
```diff
@@ -25,6 +28,19 @@ pub struct Rendered {
     pub toc: Vec<Header>,
 }
 
+#[derive(Debug)]
+struct HeaderIndex {
+    start: usize,
+    end: usize,
+    level: i32,
+}
```
Comment (Keats) [inline components/rendering/src/markdown.rs:37]: can you add some comments on what the struct is and what the fields are? `level` is seemingly obvious  but even then since it's called `HeaderIndex` and not `Header`, it isn't obvious

File: components/utils/src/vec.rs [hunk 2]
```diff
@@ -0,0 +1,44 @@
+pub trait InsertMany {
+    type Element;
+    fn insert_many(&mut self, elem_to_insert: Vec<(usize, Self::Element)>);
+}
+
+impl<T> InsertMany for Vec<T> {
+    type Element = T;
+
+    /// Efficiently insert multiple element in their specified index.
+    /// The index should be sorted in ascending order.
```
Comment (Keats) [inline components/utils/src/vec.rs]: you mean something like "the elements should be sorted in ascending order by their index"?

**Review by Keats — CHANGES_REQUESTED** [review]
Little bit of docs missing, looks good otherwise!

File: components/rendering/src/markdown.rs (hunk 1 above)
Comment (peng1999) [reply components/rendering/src/markdown.rs:37]: I renamed `HeaderIndex` to `HeaderRef`. is that better?

File: components/utils/src/vec.rs (hunk 2 above)
Comment (peng1999) [reply components/utils/src/vec.rs]: Fixed

File: components/rendering/src/markdown.rs (hunk 1 above)
Comment (peng1999) [reply components/rendering/src/markdown.rs:37]:
```rust
// tracks a header in a slice of pulldown-cmark events
#[derive(Debug)]
struct HeaderRef {
    start_idx: usize,
    end_idx: usize,
    level: i32,
}
```

**Comment by Keats** [comment]
Thanks!
